### ISSUE TITLE
WebCam.py is abnormal

### ISSUE THREAD

**Issue by monkeycc** [ipritom/flet-demo#1]
https://user-images.githubusercontent.com/6490927/205538501-739ec10a-9668-4314-811d-57400f8c3eeb.mp4

Unfortunately, the screen won't move

WebCam.py is abnormal
video.py Only the first frame will be read

`flet 0.2.2`

**Comment by ipritom** [comment]
Is it throwing any error in the terminal?

**Comment by monkeycc** [comment]
Problem solving

It's because of anti-virus software
